CREATE DATABASE todo;
USE todo;

CREATE TABLE carte (
  id INT PRIMARY KEY AUTO_INCREMENT,
  etat TINYINT NOT NULL DEFAULT 1,
  titre VARCHAR(255) NOT NULL,
  description TEXT,
  date DATETIME DEFAULT CURRENT_TIMESTAMP
);