import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import ThemeProviderClient from "./components/ThemeProviderClient";

const rubik = Rubik({
  display: "swap",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={rubik.className}>
        <ThemeProviderClient>
          <Header />
          {children}
          <Footer />
        </ThemeProviderClient>
      </body>
    </html>
  );
}
